### PR TITLE
Add more attrs

### PR DESCRIPTION
**Pull request by ehrenmurdick**

### CODE REVIEW

**Comment by ehrenmurdick** [comment]
will finish #10

**Comment by desmondrawls** [comment]
Looks good. 

Noticing mixed verb tense in commit messages. Something to consider for future commits.

**Comment by ehrenmurdick** [comment]
Good call. Present tense going forward? As in finishes the sentence "if applied, this commit will" e.g.

"Add some stuff that was needed"

Also I meant to include "finishes #10" to a commit so it would close the issue as well, but I forgot.

**Comment by desmondrawls** [comment]
Yeah, I like present tense.

**Pull request merged**
